name: solaris_ia
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.12
  - numpy
  - pytorch
  - torchvision
  - gdal
  - flask
  - tqdm
  - cairo
  - pip
  - shapely
  - geopandas
  - pip:
      - cairosvg
      - svgwrite
      - torchaudio
      - wandb